version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=testdockerdb
    ports:
      - '5435:5432'
    volumes:
      - /custom/mount:/var/lib/postgresql/data